language: python

python:
  - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
  - pip install -r requirements.txt

#before_script:
#  - mysql -e 'create database test;' -u root

script:
  - python manage.py test

after_success:
  - codecov # submit coverage